// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAerJdimkNVfHBVLTpgc9D2OqjhdqwUq7A',
    appId: '1:147605638312:web:0098b4cc4c50bfe406069d',
    messagingSenderId: '147605638312',
    projectId: 'fluttertodolist-d0ce5',
    authDomain: 'fluttertodolist-d0ce5.firebaseapp.com',
    storageBucket: 'fluttertodolist-d0ce5.appspot.com',
    measurementId: 'G-VFXDKJD8ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhcco102O2BaX4ZXpezo2aa5-xZtq2W8Q',
    appId: '1:147605638312:android:b9a4f2f357e9e69106069d',
    messagingSenderId: '147605638312',
    projectId: 'fluttertodolist-d0ce5',
    storageBucket: 'fluttertodolist-d0ce5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC06vFDmUnPA1CVVkOINbBV36jqZaNOR4M',
    appId: '1:147605638312:ios:3e19a84fcce8d6de06069d',
    messagingSenderId: '147605638312',
    projectId: 'fluttertodolist-d0ce5',
    storageBucket: 'fluttertodolist-d0ce5.appspot.com',
    iosBundleId: 'com.example.task02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC06vFDmUnPA1CVVkOINbBV36jqZaNOR4M',
    appId: '1:147605638312:ios:3e19a84fcce8d6de06069d',
    messagingSenderId: '147605638312',
    projectId: 'fluttertodolist-d0ce5',
    storageBucket: 'fluttertodolist-d0ce5.appspot.com',
    iosBundleId: 'com.example.task02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAerJdimkNVfHBVLTpgc9D2OqjhdqwUq7A',
    appId: '1:147605638312:web:54176fd5c6fddd1f06069d',
    messagingSenderId: '147605638312',
    projectId: 'fluttertodolist-d0ce5',
    authDomain: 'fluttertodolist-d0ce5.firebaseapp.com',
    storageBucket: 'fluttertodolist-d0ce5.appspot.com',
    measurementId: 'G-C8W5H7WK3E',
  );
}
